#!/bin/bash

set -euo pipefail

readonly PYTHON_VERSION=$(python3 -V 2>&1 \
  | sed -n 's/^.*\n*Python \([0-9]\+\)\.\([0-9]\+\).*/\1.\2/p')

export PYTHONPATH="/opt/drake/lib/python${PYTHON_VERSION}/site-packages${PYTHONPATH:+:${PYTHONPATH}}"

pushd "${AUTOPKGTEST_TMP}"
python3 -c 'import pydrake; print(pydrake)'
popd
